// WHAT IT IS
//   Azure Database for PostgreSQL flexible server: the same engine the agent
//   uses on the Mac, run by Azure. Two databases:
//     claims_fnol       the claims system (our MCP server's own tables)
//     claims_fnol_dbos  the agent's state and the DBOS waits (payout approvals,
//                       escalations)
//   The `vector` extension is allow-listed for Tier 7 (RAG over policy wording
//   in the same store: one database, one backup, no search bill).
//
// WHICH CONCERN IT SERVES
//   State and durable waits (stack bindings `state: azure-postgresql-flexible`,
//   `workflow: dbos`, `approval: dbos-workflows`, `retrieval: pgvector`).
//
// EXPECTED DEV COST — the one real cost of this deployment
//   Compute, Burstable B1ms: $0.0245/hour = ~$17.9 for a month left running
//   (730 h). Storage 32 GB x $0.131/GB-month = ~$4.19. Backup: 7 days, free up
//   to 100% of provisioned storage. (Azure Retail Prices API, Central India,
//   meters "B1MS" and "Storage Data Stored", read 9 Oct 2026.)
//   STOP IT WHEN IDLE: a stopped server bills storage only (~$0.14/day):
//       az postgres flexible-server stop  -g rg-claims-fnol-dev -n <server>
//       az postgres flexible-server start -g rg-claims-fnol-dev -n <server>
//   Azure starts a stopped server again by itself after 7 days, so a server
//   left alone for a month runs (and bills) about three weeks of it.
//
// AUTHENTICATION (finding F-41)
//   Microsoft Entra authentication is on, with the owner (AZURE_PRINCIPAL_ID)
//   as the Entra administrator for the portal tour. The apps still connect with
//   the password: the library's state and DBOS adapters take one database URL,
//   and an Entra login means a token as the password, refreshed hourly, which
//   no adapter does yet. So passwords are generated by azd
//   (secretOrRandomPassword) and kept in Key Vault: the administrator's, and
//   one per app login (A4: claims_agent, claims_system), which the
//   postprovision hook makes with psql as the administrator
//   (infra/hooks/db-roles.sh, infra/sql/roles.sql). The URLs built from the
//   app logins go to Key Vault too; none names the administrator. Making the agent's managed identity a database principal
//   is a library adapter (token-refreshing pool), then an overlay line.
//
// NETWORK
//   Public access with firewall rules: "Allow Azure services" (0.0.0.0, which
//   admits any Azure tenant's services, not only ours; the password is the
//   real gate), and, only if given, the owner's own IP for psql from the Mac.

targetScope = 'resourceGroup'

param location string
param name string
param tags object = {}

param administratorLogin string = 'claimsadmin'

@secure()
param administratorPassword string

@description('Entra administrator: the owner (AZURE_PRINCIPAL_ID). Empty skips it.')
param entraAdminObjectId string = ''

@description('Display name of that principal, as Entra shows it (the owner\'s UPN).')
param entraAdminName string = ''

@description('The owner\'s public IP for psql from the Mac. Empty: no rule.')
param ownerIpAddress string = ''

@description('Where the database URLs are written: agent-database-url, claims-database-url, claims-records-database-url.')
param keyVaultName string

@description('The agent\'s login (A4): owns claims_fnol_dbos. Made by infra/hooks/db-roles.sh, not here.')
param agentLogin string = 'claims_agent'

@secure()
param agentPassword string

@description('The claims system\'s login (A4): owns claims_fnol, may only SELECT agent_state.approvals in claims_fnol_dbos.')
param claimsSystemLogin string = 'claims_system'

@secure()
param claimsSystemPassword string

var databases = ['claims_fnol', 'claims_fnol_dbos']

resource server 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: name
  location: location
  tags: tags
  sku: {
    name: 'Standard_B1ms'
    tier: 'Burstable'
  }
  properties: {
    version: '16'
    administratorLogin: administratorLogin
    administratorLoginPassword: administratorPassword
    storage: {
      storageSizeGB: 32
      autoGrow: 'Disabled'
    }
    backup: {
      backupRetentionDays: 7
      geoRedundantBackup: 'Disabled'
    }
    highAvailability: {
      mode: 'Disabled'
    }
    authConfig: {
      activeDirectoryAuth: 'Enabled'
      passwordAuth: 'Enabled'
      tenantId: tenant().tenantId
    }
    network: {
      publicNetworkAccess: 'Enabled'
    }
  }
}

// `vector` (pgvector) on the allow-list; each database still runs
// CREATE EXTENSION vector when it first needs it (Tier 7).
resource extensions 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = {
  parent: server
  name: 'azure.extensions'
  properties: {
    value: 'VECTOR'
    source: 'user-override'
  }
}

@batchSize(1) // one change at a time: the server refuses concurrent child operations
resource dbs 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' = [
  for db in databases: {
    parent: server
    name: db
    properties: {
      charset: 'UTF8'
      collation: 'en_US.utf8'
    }
    dependsOn: [extensions]
  }
]

resource allowAzure 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01' = {
  parent: server
  name: 'AllowAllAzureServicesAndResourcesWithinAzureIps'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
  dependsOn: [dbs]
}

resource allowOwner 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01' = if (!empty(ownerIpAddress)) {
  parent: server
  name: 'owner-ip'
  properties: {
    startIpAddress: ownerIpAddress
    endIpAddress: ownerIpAddress
  }
  dependsOn: [allowAzure]
}

resource entraAdmin 'Microsoft.DBforPostgreSQL/flexibleServers/administrators@2024-08-01' = if (!empty(entraAdminObjectId) && !empty(entraAdminName)) {
  parent: server
  name: entraAdminObjectId
  properties: {
    principalType: 'User'
    principalName: entraAdminName
    tenantId: tenant().tenantId
  }
  dependsOn: [allowAzure, allowOwner]
}

resource vault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
  name: keyVaultName
}

// `sslmode=require`: the `azure-postgresql-flexible` state adapter refuses a
// URL that does not require TLS.
// Each URL names an app's own login (A4), never the administrator's: the
// administrator only makes the logins (infra/hooks/db-roles.sh), and no URL
// here carries its password.
var host = server.properties.fullyQualifiedDomainName
var agent = '${agentLogin}:${agentPassword}'
var claimsSystem = '${claimsSystemLogin}:${claimsSystemPassword}'

resource agentUrl 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: vault
  name: 'agent-database-url'
  properties: {
    value: 'postgresql://${agent}@${host}:5432/claims_fnol_dbos?sslmode=require'
  }
}

resource claimsUrl 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: vault
  name: 'claims-database-url'
  properties: {
    value: 'postgresql://${claimsSystem}@${host}:5432/claims_fnol?sslmode=require'
  }
}

// The claims system's own login on the agent's database: it reads approvals
// there (A3) and can do nothing else (A4, F-51).
resource claimsRecordsUrl 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: vault
  name: 'claims-records-database-url'
  properties: {
    value: 'postgresql://${claimsSystem}@${host}:5432/claims_fnol_dbos?sslmode=require'
  }
}

output name string = server.name
output host string = host
output administratorLogin string = administratorLogin
